server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-57806585.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa8nu39xkAkYZgVj5d7
            client-secret: xEk0rgzPZvIz_cilGdLqCfvzcH0h0oxnZoigN5iy
        provider:
          okta:
            issuer-uri: https://dev-57806585.okta.com/oauth2/default

microservice:
  product: http://product-service-svc/product/
  payment: http://payment-service-svc/payment/







